---
title: "Course Project - Practical Machine Learning"
author: "Alberto Macías"
date: "5/3/2021"
output: html_document
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=F, include=F}
library(ggplot2)
library(dplyr)
library(caret)
library(e1071) # For svm
```


## Feature selection and preprocessing

```{r}
training <- read.csv("./data/pml-training.csv", header = T)
training$classe <- as.factor(training$classe)
training <- training[,-1:-7]
training <- training[,-5:-29]
training <- training[,-18:-27]
training <- training[,-27:-41]
training <- training[,-30:-44]
training <- training[,-31:-40]
training <- training[,-43:-57]
training <- training[,-44:-53]
```


```{r}
set.seed(3455)
inBuild <- createDataPartition(training$classe, p=0.8, list = F)
buildData <- training[inBuild,]
validationData <- training[-inBuild,]
inTrain <- createDataPartition(buildData$classe, p=0.7, list = F)
trainData <- buildData[inTrain,]
testData <- buildData[-inTrain,]
```


```{r}
set.seed(1212)
trainClasse <- trainData$classe; trainData <- trainData[,-53]
preproc <- preProcess(trainData, method = c("pca", "center", "scale"))
preprocessedData <- predict(preproc, trainData)
preprocessedData$classe <- trainClasse
```


### Model tunning

```{r, echo=F}
set.seed(22)
rfmodel <- train(classe~., method="rf", data = preprocessedData,
                 trControl= trainControl(method = "cv", number = 3))
ldamodel <- train(classe~., method="lda", data = preprocessedData)
svmmodel <- svm(classe~., data=preprocessedData)
```

```{r}
testClasse <- testData$classe; testData <- testData[,-53]
processedTestData <- predict(preproc, testData)
processedTestData$classe <- testClasse
predrf <- predict(rfmodel, processedTestData)
predlda <- predict(ldamodel, processedTestData)
predsvm <- predict(svmmodel, processedTestData)
```

```{r}
print("Random Forest model Accuracy:")
confusionMatrix(testClasse, predrf)$overall["Accuracy"]
print("Linear Discriminant Analysis model Accuracy: ")
confusionMatrix(testClasse, predlda)$overall["Accuracy"]
print("Support Vector Machine model Accuracy:")
confusionMatrix(testClasse, predsvm)$overall["Accuracy"]
```

```{r, include=F}
gmbmodel <- train(classe~., method="gbm", data = preprocessedData)
```

```{r}
predgbm <- predict(gmbmodel, processedTestData)
print("Boosting model Accuracy:")
confusionMatrix(testClasse, predgbm)$overall["Accuracy"]
```

```{r}
predDF <- data.frame(predrf, predsvm, predgbm, classe=testClasse)
combModel <- train(classe~., method="rf", data=predDF,
                   trControl = trainControl("cv", number = 3))
```

```{r}
valClasse <- validationData$classe
validationData <- validationData[,-53]
proccesedvalData <- predict(preproc, validationData)

predrf <- predict(rfmodel, proccesedvalData)
predsvm <- predict(svmmodel, proccesedvalData)
predgbm <- predict(gmbmodel, proccesedvalData)
predDF <- data.frame(predrf, predsvm, predgbm)

predComb <- predict(combModel, predDF)
```

```{r}
print("Combined model Accuracy on validation data:")
(combined.model <- confusionMatrix(valClasse, predComb)$overall["Accuracy"])
```

```{r}
rf.model <- confusionMatrix(valClasse, predrf)$overall["Accuracy"]
svm.model <- confusionMatrix(valClasse, predsvm)$overall["Accuracy"]
gbm.model <- confusionMatrix(valClasse, predgbm)$overall["Accuracy"]
(models.accuracy <- data.frame(rf.model, svm.model, gbm.model, combined.model))
```


### Evaluating models














```{r}

```

```{r}
rfpredict <- predict(rfmodel, processedtestingData)
ldapredict <- predict(ldamodel, processedtestingData)
svmpredict <- predict(svmmodel, processedtestingData)

predDF <- data.frame(rfpredict, ldapredict, svmpredict)
```

```{r}
confusionMatrix(rfpredict, ldapredict)$overall['Accuracy']
confusionMatrix(rfpredict, svmpredict)$overall['Accuracy']
confusionMatrix(svmpredict, ldapredict)$overall['Accuracy']
```


